#!/usr/bin/env python3
"""
CPLfold Example with PARIS Data

Demonstrates using experimental PARIS data as bonus matrix
for guided RNA structure prediction with pseudoknots.

Example data: bpRNA_RFAM_5220 (snoRNA SNORA73, 207nt)
PARIS data extracted using extract_paris_scores.py based on IRIS method.

Reference:
- IRIS: https://github.com/qczhang/IRIS
- Zhang et al. (2021) Genome Biology

Author: Ke Wang
"""

import sys
import os
import numpy as np

# Add current directory to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from CPLfold import two_phase_pseudoknot_fold


def load_sequence_from_dbn(dbn_file):
    """Load sequence from .dbn file."""
    with open(dbn_file, 'r') as f:
        lines = f.readlines()

    # Skip comment lines, get sequence (first non-comment, non-structure line)
    for line in lines:
        line = line.strip()
        if line and not line.startswith('#') and not line.startswith('.') and not line.startswith('('):
            return line
    return None


def load_reference_structure(dbn_file):
    """Load reference structure from .dbn file."""
    with open(dbn_file, 'r') as f:
        lines = f.readlines()

    # Get the last non-empty line (structure)
    for line in reversed(lines):
        line = line.strip()
        if line and (line.startswith('.') or line.startswith('(')):
            return line
    return None


def load_paris_scores(score_file, seq_len):
    """
    Load PARIS basepair scores into a bonus matrix.

    File format: i j score (1-indexed positions)
    Generated by extract_paris_scores.py
    """
    bonus_matrix = np.zeros((seq_len, seq_len), dtype=np.float32)

    with open(score_file, 'r') as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 3:
                i = int(parts[0]) - 1  # Convert to 0-indexed
                j = int(parts[1]) - 1
                score = float(parts[2])

                if 0 <= i < seq_len and 0 <= j < seq_len:
                    bonus_matrix[i, j] = score
                    bonus_matrix[j, i] = score  # Symmetric

    return bonus_matrix


def calculate_f1(pred_structure, ref_structure):
    """Calculate F1 score between predicted and reference structures."""
    def get_pairs(structure):
        pairs = set()
        stack = []
        for i, c in enumerate(structure):
            if c == '(':
                stack.append(i)
            elif c == ')' and stack:
                j = stack.pop()
                pairs.add((j, i))
        return pairs

    pred_pairs = get_pairs(pred_structure)
    ref_pairs = get_pairs(ref_structure)

    if not pred_pairs and not ref_pairs:
        return 1.0
    if not pred_pairs or not ref_pairs:
        return 0.0

    tp = len(pred_pairs & ref_pairs)
    precision = tp / len(pred_pairs) if pred_pairs else 0
    recall = tp / len(ref_pairs) if ref_pairs else 0

    if precision + recall == 0:
        return 0.0

    f1 = 2 * precision * recall / (precision + recall)
    return f1


def main():
    # Data paths - using PARIS data from IRIS dataset
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.join(script_dir, "data")
    example_id = "bpRNA_RFAM_5220"

    dbn_file = os.path.join(data_dir, f"{example_id}.dbn")
    score_file = os.path.join(data_dir, f"{example_id}_paris_scores.txt")

    print("=" * 70)
    print("CPLfold Example with PARIS Data")
    print("=" * 70)
    print(f"\nExample: {example_id} (snoRNA SNORA73)")
    print("PARIS data: 9592 valid chimeric reads")

    # Load sequence and reference structure
    sequence = load_sequence_from_dbn(dbn_file)
    ref_structure = load_reference_structure(dbn_file)
    seq_len = len(sequence)

    print(f"Sequence length: {seq_len}")
    print(f"Sequence: {sequence}")
    print(f"Reference: {ref_structure}")

    # Load PARIS bonus matrix
    bonus_matrix = load_paris_scores(score_file, seq_len)
    nonzero = np.count_nonzero(bonus_matrix)
    print(f"\nPARIS bonus matrix: {nonzero // 2} basepair scores loaded")
    print(f"Score range: {bonus_matrix[bonus_matrix > 0].min():.4f} - {bonus_matrix.max():.4f}")

    # =========================================================================
    # Test 1: Without bonus matrix (alpha = 0)
    # =========================================================================
    print("\n" + "-" * 70)
    print("Test 1: Without PARIS data (alpha = 0)")
    print("-" * 70)

    results_no_bonus = two_phase_pseudoknot_fold(
        sequence,
        beam_size=100,
        energy_delta=5.0,
        max_phase1=5,
        alpha=0.0,
        beta=0.0,
        verbose=False
    )

    if results_no_bonus:
        best = results_no_bonus[0]
        f1 = calculate_f1(best['structure'], ref_structure)
        print(f"Best structure: {best['structure']}")
        print(f"Energy: {best['energy']:.2f} kcal/mol")
        print(f"F1 score: {f1:.3f}")

    # =========================================================================
    # Test 2: With PARIS bonus matrix (alpha = 0.5)
    # =========================================================================
    print("\n" + "-" * 70)
    print("Test 2: With PARIS data (alpha = 0.5)")
    print("-" * 70)

    results_with_bonus = two_phase_pseudoknot_fold(
        sequence,
        beam_size=100,
        energy_delta=5.0,
        max_phase1=5,
        bonus_matrix=bonus_matrix,
        alpha=0.5,
        beta=0.0,
        verbose=False
    )

    if results_with_bonus:
        best = results_with_bonus[0]
        f1 = calculate_f1(best['structure'], ref_structure)
        print(f"Best structure: {best['structure']}")
        print(f"Energy: {best['energy']:.2f} kcal/mol")
        print(f"F1 score: {f1:.3f}")

    # =========================================================================
    # Test 3: With PARIS bonus matrix and beta (alpha = 0.5, beta = 0.3)
    # =========================================================================
    print("\n" + "-" * 70)
    print("Test 3: With PARIS data + pseudoknot preference (alpha=0.5, beta=0.3)")
    print("-" * 70)

    results_with_beta = two_phase_pseudoknot_fold(
        sequence,
        beam_size=100,
        energy_delta=5.0,
        max_phase1=5,
        bonus_matrix=bonus_matrix,
        alpha=0.5,
        beta=0.3,
        verbose=False
    )

    if results_with_beta:
        best = results_with_beta[0]
        f1 = calculate_f1(best['structure'], ref_structure)
        print(f"Best structure: {best['structure']}")
        print(f"Energy: {best['energy']:.2f} kcal/mol")
        print(f"Type: {best['type']}")
        print(f"F1 score: {f1:.3f}")

        # Show pseudoknot structures if any
        pk_structs = [r for r in results_with_beta if r['type'] == 'pseudoknot']
        if pk_structs:
            print(f"\nFound {len(pk_structs)} pseudoknot structure(s)")

    # =========================================================================
    # Summary
    # =========================================================================
    print("\n" + "=" * 70)
    print("Summary")
    print("=" * 70)
    print(f"Reference:          {ref_structure}")
    if results_no_bonus:
        f1_no = calculate_f1(results_no_bonus[0]['structure'], ref_structure)
        print(f"alpha=0:            {results_no_bonus[0]['structure']} (F1={f1_no:.3f})")
    if results_with_bonus:
        f1_with = calculate_f1(results_with_bonus[0]['structure'], ref_structure)
        print(f"alpha=0.5:          {results_with_bonus[0]['structure']} (F1={f1_with:.3f})")
    if results_with_beta:
        f1_beta = calculate_f1(results_with_beta[0]['structure'], ref_structure)
        print(f"alpha=0.5,beta=0.3: {results_with_beta[0]['structure']} (F1={f1_beta:.3f})")


if __name__ == "__main__":
    main()
